name: Main

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: myservice
  REGION: us-central1

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: go test ./...

    - name: Build Container
      run: docker build --target prod -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .

    - name: Setup Cloud SDK
      if: github.ref == 'refs/heads/main'
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      if: github.ref == 'refs/heads/main'
      run: gcloud auth configure-docker

    - name: Push Container
      if: github.ref == 'refs/heads/main'
      run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      if: github.ref == 'refs/heads/main'
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.4.0
      with:
        service: ${{ env.SERVICE }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        region: ${{ env.REGION }}

    - name: Show Output
      if: github.ref == 'refs/heads/main'
      run: echo ${{ steps.deploy.outputs.url }}